/* ============================================================
   Formula reference.
   Each entry has one honest example with the result it actually
   produces. Entries unlock when the module that teaches them is
   reached; before that they appear only as a list of names, so
   you can see what is coming without pretending you know it.
   ============================================================ */

const REFERENCE = [
  /* ---- Module 2: formulas that think ---- */
  { name: "SUM", module: "m2", tags: ["add", "total"],
    what: "Adds up the numbers in a range. Ignores text and blanks without complaining, which is a convenience and a hazard.",
    syntax: "=SUM(range)", example: "=SUM(B2:B20)", result: "the total of B2 to B20",
    note: "If the total looks low, check for numbers stored as text inside the range." },
  { name: "AVERAGE", module: "m2", tags: ["mean"],
    what: "The mean: total divided by how many numbers there are. Skips blanks and text.",
    syntax: "=AVERAGE(range)", example: "=AVERAGE(B2:B20)", result: "the mean of the numbers in B2 to B20",
    note: "A blank cell and a zero are not the same thing here. A blank is left out; a zero is averaged in and drags the mean down." },
  { name: "MIN", module: "m2", tags: ["smallest", "lowest"],
    what: "The smallest number in a range.",
    syntax: "=MIN(range)", example: "=MIN(B2:B20)", result: "the lowest value" },
  { name: "MAX", module: "m2", tags: ["largest", "highest"],
    what: "The largest number in a range.",
    syntax: "=MAX(range)", example: "=MAX(B2:B20)", result: "the highest value" },
  { name: "COUNT", module: "m2", tags: ["how many", "numbers"],
    what: "Counts how many cells in a range hold a number. Text and blanks are not counted.",
    syntax: "=COUNT(range)", example: "=COUNT(B2:B20)", result: "how many of those 19 cells hold numbers",
    note: "Comparing COUNT with COUNTA on the same range is the quickest way to find out how many values are stored as text." },
  { name: "COUNTA", module: "m2", tags: ["how many", "not empty"],
    what: "Counts how many cells are not empty, whatever they contain.",
    syntax: "=COUNTA(range)", example: "=COUNTA(A2:A20)", result: "how many of those cells have something in them" },
  { name: "ROUND", module: "m2", tags: ["decimal places", "rounding"],
    what: "Rounds a number to a given number of decimal places, and actually changes the value rather than just the display.",
    syntax: "=ROUND(number, digits)", example: "=ROUND(2.675, 2)", result: "2.68",
    note: "Use a negative digits argument to round to tens or hundreds: =ROUND(1234, -2) gives 1200." },
  { name: "ROUNDUP", module: "m2", tags: ["ceiling"],
    what: "Rounds away from zero, regardless of the digit that follows.",
    syntax: "=ROUNDUP(number, digits)", example: "=ROUNDUP(2.01, 0)", result: "3" },
  { name: "ROUNDDOWN", module: "m2", tags: ["floor", "truncate"],
    what: "Rounds towards zero, regardless of the digit that follows.",
    syntax: "=ROUNDDOWN(number, digits)", example: "=ROUNDDOWN(2.99, 0)", result: "2" },
  { name: "ABS", module: "m2", tags: ["absolute", "positive"],
    what: "The size of a number, ignoring its sign. Useful when a difference could go either way and you only care how big it is.",
    syntax: "=ABS(number)", example: "=ABS(-42)", result: "42" },

  /* ---- Module 3: logic and conditions ---- */
  { name: "IF", module: "m3", tags: ["condition", "logic", "then"],
    what: "Tests something, then returns one value if it is true and another if it is false.",
    syntax: "=IF(test, value_if_true, value_if_false)", example: '=IF(B2>500, "Review", "OK")', result: 'Review when B2 is over 500, otherwise OK',
    note: "Text inside a formula always needs quotation marks. Numbers never do." },
  { name: "IFS", module: "m3", tags: ["multiple conditions", "nested"],
    what: "Tests several conditions in order and returns the value for the first one that is true. Easier to read than nesting IF inside IF.",
    syntax: "=IFS(test1, value1, test2, value2, ...)", example: '=IFS(B2>1000,"High",B2>500,"Medium",TRUE,"Low")', result: "one of High, Medium or Low",
    note: "Order matters, because the first match wins. Finish with TRUE as a catch-all, otherwise a value matching nothing returns #N/A." },
  { name: "AND", module: "m3", tags: ["both", "all"],
    what: "TRUE only when every condition given is true.",
    syntax: "=AND(test1, test2, ...)", example: "=AND(B2>500, C2=\"London\")", result: "TRUE only when both hold" },
  { name: "OR", module: "m3", tags: ["either", "any"],
    what: "TRUE when at least one condition is true.",
    syntax: "=OR(test1, test2, ...)", example: '=OR(C2="London", C2="Leeds")', result: "TRUE for either city" },
  { name: "NOT", module: "m3", tags: ["opposite", "invert"],
    what: "Flips TRUE to FALSE and back.",
    syntax: "=NOT(test)", example: '=NOT(C2="London")', result: "TRUE for every city except London" },
  { name: "COUNTIF", module: "m3", tags: ["count", "condition", "how many"],
    what: "Counts the cells in a range that meet one condition.",
    syntax: "=COUNTIF(range, criteria)", example: '=COUNTIF(C2:C500, "London")', result: "how many rows say London",
    note: "Criteria go in quotation marks even when they contain an operator: \">500\", not >500." },
  { name: "COUNTIFS", module: "m3", tags: ["count", "several conditions"],
    what: "Counts rows meeting several conditions at once.",
    syntax: "=COUNTIFS(range1, criteria1, range2, criteria2, ...)", example: '=COUNTIFS(C2:C500,"London",B2:B500,">500")', result: "how many London rows are also over 500",
    note: "Every range must be the same size and shape, or you get #VALUE!." },
  { name: "SUMIF", module: "m3", tags: ["total", "condition"],
    what: "Adds the values that meet one condition.",
    syntax: "=SUMIF(test_range, criteria, sum_range)", example: '=SUMIF(C2:C500,"London",B2:B500)', result: "the total of B for every London row",
    note: "The awkward part: the range being tested comes first and the range being added comes last. SUMIFS reverses this, which catches everyone out at least once." },
  { name: "SUMIFS", module: "m3", tags: ["total", "several conditions"],
    what: "Adds the values that meet several conditions.",
    syntax: "=SUMIFS(sum_range, range1, criteria1, ...)", example: '=SUMIFS(B2:B500,C2:C500,"London",D2:D500,">=01/03/2024")', result: "the London total from March onwards",
    note: "Here the range being added comes first. Compare with SUMIF, where it comes last." },
  { name: "AVERAGEIFS", module: "m3", tags: ["mean", "conditions"],
    what: "The mean of the values meeting several conditions.",
    syntax: "=AVERAGEIFS(avg_range, range1, criteria1, ...)", example: '=AVERAGEIFS(B2:B500,C2:C500,"Leeds")', result: "the average amount in Leeds" },
  { name: "IFERROR", module: "m3", tags: ["error", "tidy"],
    what: "Returns your own value when a formula would otherwise show an error.",
    syntax: "=IFERROR(formula, value_if_error)", example: '=IFERROR(A2/B2, "")', result: "blank instead of #DIV/0!",
    note: "Use it to tidy an output people will read, never to hide an error you have not understood. Hiding #N/A from a lookup usually hides a data problem." },

  /* ---- Module 4: cleaning ---- */
  { name: "TRIM", module: "m4", tags: ["spaces", "clean", "tidy up text"],
    what: "Removes spaces from the start and end of text, and collapses runs of spaces in the middle down to one.",
    syntax: "=TRIM(text)", example: '=TRIM("  Acme   Ltd  ")', result: '"Acme Ltd"',
    note: "The commonest single fix in data cleaning. Trailing spaces are invisible and stop lookups matching." },
  { name: "PROPER", module: "m4", tags: ["capitalise", "case"],
    what: "Capitalises the first letter of each word and lowercases the rest.",
    syntax: "=PROPER(text)", example: '=PROPER("ACME trading ltd")', result: '"Acme Trading Ltd"',
    note: "It capitalises after any non-letter, so \"o'brien\" becomes \"O'Brien\" but \"don't\" becomes \"Don'T\". Check names by eye afterwards." },
  { name: "UPPER", module: "m4", tags: ["capitals", "case"],
    what: "Converts text to capitals. Useful for making codes comparable.",
    syntax: "=UPPER(text)", example: '=UPPER("gb12 abcd")', result: '"GB12 ABCD"' },
  { name: "LOWER", module: "m4", tags: ["case"],
    what: "Converts text to lower case.",
    syntax: "=LOWER(text)", example: '=LOWER("Smith@Example.COM")', result: '"smith@example.com"' },
  { name: "LEN", module: "m4", tags: ["length", "characters"],
    what: "How many characters are in the text, spaces included.",
    syntax: "=LEN(text)", example: '=LEN("Acme ")', result: "5",
    note: "Comparing LEN before and after TRIM is the quickest way to prove a cell has hidden spaces." },
  { name: "LEFT", module: "m4", tags: ["first characters", "split"],
    what: "Takes a number of characters from the start of the text.",
    syntax: "=LEFT(text, count)", example: '=LEFT("GB29NWBK", 2)', result: '"GB"' },
  { name: "RIGHT", module: "m4", tags: ["last characters", "split"],
    what: "Takes a number of characters from the end of the text.",
    syntax: "=RIGHT(text, count)", example: '=RIGHT("INV-2045", 4)', result: '"2045"' },
  { name: "MID", module: "m4", tags: ["middle", "extract"],
    what: "Takes characters from the middle, starting at a position you give.",
    syntax: "=MID(text, start, count)", example: '=MID("GB29NWBK", 3, 2)', result: '"29"' },
  { name: "FIND", module: "m4", tags: ["position", "search"],
    what: "The position of one piece of text inside another. Case sensitive.",
    syntax: "=FIND(needle, haystack)", example: '=FIND("@", "j.smith@example.com")', result: "8",
    note: "Returns #VALUE! when not found, so it is usually wrapped in IFERROR." },
  { name: "SEARCH", module: "m4", tags: ["position", "case insensitive"],
    what: "Like FIND, but ignores capitalisation and allows wildcards.",
    syntax: "=SEARCH(needle, haystack)", example: '=SEARCH("SMITH", "j.smith@example.com")', result: "3" },
  { name: "SUBSTITUTE", module: "m4", tags: ["replace", "swap"],
    what: "Replaces one piece of text with another, everywhere or at a chosen occurrence.",
    syntax: "=SUBSTITUTE(text, old, new, [which])", example: '=SUBSTITUTE("01-02-2024","-","/")', result: '"01/02/2024"' },
  { name: "TEXT", module: "m4", tags: ["format as text", "display"],
    what: "Turns a number or date into text in a format you specify.",
    syntax: "=TEXT(value, format)", example: '=TEXT(45352, "mmm yyyy")', result: '"Mar 2024"',
    note: "The output is text, so it can no longer be added up or sorted as a number. Use it for labels, not for data." },
  { name: "VALUE", module: "m4", tags: ["text to number", "convert"],
    what: "Turns text that looks like a number into an actual number.",
    syntax: "=VALUE(text)", example: '=VALUE("1,250")', result: "1250" },
  { name: "DATEVALUE", module: "m4", tags: ["text to date", "convert"],
    what: "Turns text that looks like a date into a real date.",
    syntax: "=DATEVALUE(text)", example: '=DATEVALUE("17/03/2024")', result: "45368, shown as a date once formatted",
    note: "The result is the day count. Apply a date format to see it as a date." },
  { name: "TEXTSPLIT", module: "m4", tags: ["split", "columns", "separate"],
    what: "Splits text into separate cells at a delimiter.",
    syntax: "=TEXTSPLIT(text, delimiter)", example: '=TEXTSPLIT("Smith, John", ", ")', result: 'two cells: "Smith" and "John"',
    note: "Newer than Text to Columns and better, because it updates when the source changes rather than being a one-off." },
  { name: "TEXTBEFORE", module: "m4", tags: ["split", "extract"],
    what: "Everything before the first occurrence of a delimiter.",
    syntax: "=TEXTBEFORE(text, delimiter)", example: '=TEXTBEFORE("j.smith@example.com","@")', result: '"j.smith"' },
  { name: "TEXTAFTER", module: "m4", tags: ["split", "extract"],
    what: "Everything after the first occurrence of a delimiter.",
    syntax: "=TEXTAFTER(text, delimiter)", example: '=TEXTAFTER("j.smith@example.com","@")', result: '"example.com"' },
  { name: "CONCAT", module: "m4", tags: ["join", "combine"],
    what: "Joins pieces of text together.",
    syntax: "=CONCAT(a, b, ...)", example: '=CONCAT(A2, " ", B2)', result: "the two cells with a space between",
    note: "The ampersand does the same thing and is shorter: =A2 & \" \" & B2. Most people use the ampersand." },
  { name: "TEXTJOIN", module: "m4", tags: ["join", "list", "separator"],
    what: "Joins text with a separator, and can skip blanks.",
    syntax: "=TEXTJOIN(separator, ignore_empty, range)", example: '=TEXTJOIN(", ", TRUE, A2:A5)', result: "a comma-separated list, blanks left out" },
  { name: "UNIQUE", module: "m4", tags: ["distinct", "duplicates", "list"],
    what: "Returns the distinct values from a range, spilling down the sheet.",
    syntax: "=UNIQUE(range)", example: "=UNIQUE(C2:C500)", result: "each city once",
    note: "Unlike Remove Duplicates, it does not alter the source data, which makes it the safer tool." },

  /* ---- Module 5: lookups ---- */
  { name: "XLOOKUP", module: "m5", tags: ["lookup", "find", "match", "join"],
    what: "Finds a value in one column and returns the matching value from another. Exact match by default, and it can look leftwards.",
    syntax: "=XLOOKUP(value, lookup_range, return_range, [if_not_found], [match_mode])", example: '=XLOOKUP(A2, Prices!A:A, Prices!C:C, "not on file")', result: "the price, or your own message",
    note: "The if_not_found argument is the reason to prefer this over everything else. It removes the need to wrap the whole thing in IFERROR." },
  { name: "VLOOKUP", module: "m5", tags: ["lookup", "legacy", "interview"],
    what: "The older lookup. Searches the first column of a block and returns a value from a numbered column to its right.",
    syntax: "=VLOOKUP(value, table, column_number, [FALSE])", example: '=VLOOKUP(A2, Prices!A:C, 3, FALSE)', result: "the value from the third column",
    note: "Three real flaws: it cannot look left, the column number breaks if a column is inserted, and leaving off the final FALSE gives approximate matching, which returns confidently wrong answers on unsorted data. Learn it because interviews ask for it." },
  { name: "INDEX", module: "m5", tags: ["lookup", "position"],
    what: "Returns the value at a given position in a range.",
    syntax: "=INDEX(range, row, [column])", example: "=INDEX(C2:C500, 12)", result: "the twelfth price" },
  { name: "MATCH", module: "m5", tags: ["lookup", "position", "find row"],
    what: "Returns the position of a value within a range, rather than the value itself.",
    syntax: "=MATCH(value, range, 0)", example: '=MATCH("B200", A2:A500, 0)', result: "the row number within that range",
    note: "The 0 means exact match and is almost always what you want. Paired with INDEX it does everything VLOOKUP does, without the flaws." },
  { name: "IFNA", module: "m5", tags: ["error", "not found"],
    what: "Catches only #N/A, leaving other errors visible.",
    syntax: "=IFNA(formula, value)", example: '=IFNA(VLOOKUP(A2,P!A:C,3,FALSE), "not on file")', result: "your message instead of #N/A",
    note: "Better than IFERROR around a lookup, because a genuine #REF! or #VALUE! still shows rather than being swallowed." },

  /* ---- Module 7: charts and presentation ---- */
  { name: "COUNTBLANK", module: "m7", tags: ["empty", "missing", "gaps"],
    what: "How many cells in a range are empty. A quick data quality check before you chart anything.",
    syntax: "=COUNTBLANK(range)", example: "=COUNTBLANK(B2:B500)", result: "the number of gaps" },

  /* ---- Module 8: finding the needle ---- */
  { name: "SUMPRODUCT", module: "m8", tags: ["array", "conditions", "count"],
    what: "Multiplies ranges together element by element and adds the results. With conditions in brackets it counts or totals rows matching several tests at once.",
    syntax: "=SUMPRODUCT((test1)*(test2))", example: '=SUMPRODUCT((C2:C500="Leeds")*(B2:B500>500))', result: "how many rows satisfy both",
    note: "COUNTIFS is clearer for straightforward cases. SUMPRODUCT earns its place when the conditions compare two columns to each other." },
  { name: "EXACT", module: "m8", tags: ["case sensitive", "compare"],
    what: "Compares two pieces of text including capitalisation. Excel's normal equals sign ignores case.",
    syntax: "=EXACT(a, b)", example: '=EXACT("ABC","abc")', result: "FALSE" },
  { name: "MOD", module: "m8", tags: ["remainder", "round numbers"],
    what: "The remainder after division. Finding amounts that divide exactly by 100 or 1000 is a standard test for artificially round transactions.",
    syntax: "=MOD(number, divisor)", example: "=MOD(4500, 500)", result: "0, so 4500 is an exact multiple of 500" },
  { name: "MAXIFS", module: "m8", tags: ["largest", "conditions", "previous"],
    what: "The largest value meeting several conditions. The standard way to find the most recent earlier date on an account, which is how you measure a dormancy gap.",
    syntax: "=MAXIFS(max_range, range1, criteria1, ...)", example: '=MAXIFS(C2:C90, B2:B90, B2, C2:C90, "<"&C2)', result: "the previous payment date for that account",
    note: "Returns 0 when nothing matches, so guard the first row of each group with an IF or you get a gap of about 45,000 days." },
  { name: "MINIFS", module: "m8", tags: ["smallest", "conditions"],
    what: "The smallest value meeting several conditions. The mirror of MAXIFS, useful for a first-seen date.",
    syntax: "=MINIFS(min_range, range1, criteria1, ...)", example: '=MINIFS(C2:C90, B2:B90, B2)', result: "that account's earliest date" },
  { name: "EOMONTH", module: "m8", tags: ["month end", "date"],
    what: "The last day of a month, a given number of months from a date.",
    syntax: "=EOMONTH(date, months)", example: "=EOMONTH(DATE(2024,2,10), 0)", result: "29 February 2024" },
  { name: "NETWORKDAYS", module: "m8", tags: ["working days", "date"],
    what: "Counts working days between two dates, weekends excluded.",
    syntax: "=NETWORKDAYS(start, end)", example: "=NETWORKDAYS(DATE(2024,3,4), DATE(2024,3,8))", result: "5" },

  /* ---- Module 9: statistics ---- */
  { name: "MEDIAN", module: "m9", tags: ["middle", "average", "typical"],
    what: "The middle value when everything is lined up in order. Unlike the mean, one enormous outlier barely moves it.",
    syntax: "=MEDIAN(range)", example: "=MEDIAN(B2:B500)", result: "the middle amount",
    note: "When mean and median differ a lot, the distribution is skewed and quoting the mean alone is misleading." },
  { name: "STDEV.S", module: "m9", tags: ["spread", "deviation", "unusual"],
    what: "Standard deviation of a sample: roughly, how far a typical value sits from the mean.",
    syntax: "=STDEV.S(range)", example: "=STDEV.S(B2:B500)", result: "the spread of the amounts",
    note: "Use STDEV.P only when your rows are the entire population rather than a sample of it. In practice you almost always want STDEV.S." },
  { name: "PERCENTILE.INC", module: "m9", tags: ["percentile", "rank", "threshold"],
    what: "The value below which a given proportion of the data falls.",
    syntax: "=PERCENTILE.INC(range, p)", example: "=PERCENTILE.INC(B2:B500, 0.95)", result: "the 95th percentile amount" },
  { name: "STANDARDIZE", module: "m9", tags: ["z score", "anomaly"],
    what: "Converts a value into a z score: how many standard deviations it sits from the mean.",
    syntax: "=STANDARDIZE(x, mean, standard_deviation)", example: "=STANDARDIZE(9, 5, 2)", result: "2, meaning two standard deviations above the mean",
    note: "A z score above 3 is genuinely unusual for roughly bell-shaped data. Transaction amounts are rarely bell-shaped, so treat it as a ranking device rather than a probability." },
  { name: "CORREL", module: "m9", tags: ["correlation", "relationship"],
    what: "How closely two columns move together, from -1 through 0 to 1.",
    syntax: "=CORREL(range1, range2)", example: "=CORREL(B2:B100, C2:C100)", result: "a number between -1 and 1",
    note: "It measures straight-line association only, and says nothing whatever about cause. Two things can correlate at 0.9 with no connection at all." },
  { name: "LARGE", module: "m9", tags: ["top", "nth largest"],
    what: "The nth largest value in a range.",
    syntax: "=LARGE(range, n)", example: "=LARGE(B2:B500, 3)", result: "the third largest amount" },
  { name: "SMALL", module: "m9", tags: ["bottom", "nth smallest"],
    what: "The nth smallest value in a range.",
    syntax: "=SMALL(range, n)", example: "=SMALL(B2:B500, 3)", result: "the third smallest amount" },
  { name: "RANK.EQ", module: "m9", tags: ["rank", "position", "league"],
    what: "The position of a value within a list, with ties sharing a rank.",
    syntax: "=RANK.EQ(value, range, [order])", example: "=RANK.EQ(B2, B2:B500)", result: "where B2 sits, largest first by default" },

  /* ---- Module 10: analysis for writing ---- */
  { name: "SORT", module: "m10", tags: ["order", "arrange"],
    what: "Returns a range sorted, spilling into new cells and leaving the original untouched.",
    syntax: "=SORT(range, [column], [order])", example: "=SORT(A2:C50, 3, -1)", result: "the block ordered by the third column, largest first",
    note: "Safer than the Sort button when the source data must stay in its original order for an audit trail." },
  { name: "FILTER", module: "m10", tags: ["subset", "where"],
    what: "Returns only the rows meeting a condition, spilling into new cells.",
    syntax: "=FILTER(range, condition, [if_empty])", example: '=FILTER(A2:C500, C2:C500="Leeds", "none")', result: "just the Leeds rows",
    note: "Unlike the Filter button this is a live formula, so it updates when the source data changes." },
  { name: "YEAR", module: "m10", tags: ["date", "extract"],
    what: "The year from a date.",
    syntax: "=YEAR(date)", example: "=YEAR(DATE(2024,3,1))", result: "2024" },
  { name: "MONTH", module: "m10", tags: ["date", "extract"],
    what: "The month number from a date, 1 to 12.",
    syntax: "=MONTH(date)", example: "=MONTH(DATE(2024,3,1))", result: "3",
    note: "To group a chart by month, add a helper column of =TEXT(date,\"yyyy-mm\"), which sorts correctly. =TEXT(date,\"mmm\") does not, because April sorts before January." }
];
